### ISSUE TITLE
oltpbench: tpcc hangs

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1042]
[tpcc_config.xml.txt](https://github.com/cmu-db/peloton/files/1619291/tpcc_config.xml.txt)

Trying to run oltpbench tpcc, it hangs on loading data. Insufficient information for any diagnosis.

```
09:27:43,498 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: /home/pakhtar/proj/saved_configs/tpcc_config.xml
Type:          PELOTON
Driver:        org.postgresql.Driver
URL:           jdbc:postgresql://localhost:15721/tpcc
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  1.0

09:27:43,499 (DBWorkload.java:260) INFO  - ======================================================================
09:27:43,511 (DBWorkload.java:512) INFO  - Creating new TPCC database...
09:27:43,838 (DBWorkload.java:514) INFO  - Finished!
09:27:43,838 (DBWorkload.java:515) INFO  - ======================================================================
09:27:43,838 (DBWorkload.java:538) INFO  - Loading data into TPCC database...
```
Peloton output:
```
....


2018-01-10 09:48:09 [/home/proj/peloton-pa/peloton/src/network/network_connection.cpp:605:CloseSocket] DEBUG - Already Closed the connection 56
2018-01-10 09:48:09 [/home/proj/peloton-pa/peloton/src/network/network_connection.cpp:323:FlushWriteBuffer] ERROR - Fatal error during write, errno 32
2018-01-10 09:48:09 [/home/proj/peloton-pa/peloton/src/network/network_connection.cpp:788:StateMachine] ERROR - Error during write, closing connection
2018-01-10 09:48:09 [/home/proj/peloton-pa/peloton/src/network/network_connection.cpp:589:CloseSocket] DEBUG - Attempt to close the connection 57
2018-01-10 09:48:09 [/home/proj/peloton-pa/peloton/src/network/network_connection.cpp:605:CloseSocket] DEBUG - Already Closed the connection 57

```
config file attached, as generated by benchmark.py. Test run manually using the attached config file.
Other configuration:
- Ubuntu 14.04 LTS
- debug build

**Comment by pervazea** [comment]
This should be re-run with log4j debug logging, to see if there actually is progress being made.

**Comment by pervazea** [comment]
Not conclusive, but I'm reasonably convinced that I'm seeing the same problem as observed with TATP, i.e. the configuration uses a large number of records and the loading of those records is slow. Since TPCC provides almost no progress indicators (even with debug logging enabled), it looks like things are hung. Periodic progress updates are needed from oltpbench for TPCC. Also, the configuration likely needs adjusting to run in a reasonable period of time.

**Comment by neo-apz** [comment]
How long should this roughly take?

**Comment by apavlo** [comment]
@neo-apz It's unclear. It's a unknown bug. If we knew what was causing the problem then we would know how to fix it.

**Comment by neo-apz** [comment]
No I meant how long the loading process takes.
Because it's not clear whether it has hung or it is still loading the data. I can see it's consuming both CPU and memory resources, but it's still unclear whether it's actually making any progress.
So I'll really appreciate it if I know how long it roughly takes to load all the data, so that I know whether it's hung or not.
Thanks

**Comment by pervazea** [comment]
Loading time depends upon the configuration, what you have set in tpcc_config.xml. I'm using a scalefactor of 1, and loading time is still a problem. I don't remember the exact numbers, but when I extrapolated from progress last time I made observations, the loading time was going to be in the hours. 

See the attached file. Rename it to log4j.properties  and place in the working directory from where you run oltpbench.. You can adjust logging levels overall and for specific benchmarks. You'll have to look at the TPCCLoader.java file to see what it uses and logs.

[log4j_properties.txt](https://github.com/cmu-db/peloton/files/1720146/log4j_properties.txt)

**Comment by pervazea** [comment]
Against current master (release build). 

21:32:08,381 (Worker.java:503) ERROR - Fatal error when invoking NewOrder/01
java.lang.RuntimeException: C_D_ID=1 C_ID=1275 not found!
	at com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder.newOrderTransaction(NewOrder.java:192)
	at com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder.run(NewOrder.java:158)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCWorker.executeWork(TPCCWorker.java:74)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
	at com.oltpbenchmark.api.Worker.run(Worker.java:296)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pervazea** [comment]
Master (with modified oltpbench to avoid #1197)

Release build, codegen on:
*** Error in `./peloton': double free or corruption (fasttop): 0x00007fb1bd463b70 ***
======= 

Release build, codegen off:
*** Error in `./peloton': double free or corruption (fasttop): 0x00007f740cc51110 ***

pa_insert branch:
Release build, codegen on
*** Error in `./peloton': munmap_chunk(): invalid pointer: 0x00007f900cc3ff00 ***

Release build, codegen off
*** Error in `./peloton': munmap_chunk(): invalid pointer: 0x00007fc784c3be60 ***

**Comment by pervazea** [comment]
pa_insert branch, release build, unmodified oltpbench, codegen on:
*** Error in `./peloton': corrupted size vs. prev_size: 0x00007efda0c402c0 ***

ditto, codegen off:
*** Error in `./peloton': corrupted size vs. prev_size: 0x00007f3d314550e0 ***

**Comment by pervazea** [comment]
I ran tpcc against master, to determine if the memory problem was in the updated code. 

The address sanitizer caught a problem in the new code. With a fix for that, TPCC now runs.
That master was failing, but with the updates, TPCC now runs, would imply the old insert code was the source of the problem with master. Should be non-issue once the new code is merged.

**Comment by apavlo** [comment]
@pervazea This is great news!
