### ISSUE TITLE
oltpbench: smallbank fails

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1044]
When running oltpbench smallbank manually, the benchmark never completes.

Peloton (debug build), runs and continuously produces the output below:
```
...
4:CheckForeignKeyConstraints] INFO  - BEGIN checking referred table
2018-01-10 10:58:25 [/home/proj/peloton-pa/peloton/src/storage/data_table.cpp:594:CheckForeignKeyConstraints] INFO  - BEGIN checking referred table
2018-01-10 10:58:25 [/home/proj/peloton-pa/peloton/src/storage/data_table.cpp:594:CheckForeignKeyConstraints] INFO  - BEGIN checking referred table
2018-01-10 10:58:25 [/home/proj/peloton-pa/peloton/src/storage/data_table.cpp:594:CheckForeignKeyConstraints] INFO  - BEGIN checking referred table
2018-01-10 10:58:25 [/home/proj/peloton-pa/peloton/src/storage/data_table.cpp:594:CheckForeignKeyConstraints] INFO  - BEGIN checking referred table
```

oltpbench produces:
```
10:34:36,030 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     SMALLBANK {com.oltpbenchmark.benchmarks.smallbank.SmallBankBenchmark}
Configuration: /home/pakhtar/proj/saved_configs/smallbank_config.xml
Type:          PELOTON
Driver:        org.postgresql.Driver
URL:           jdbc:postgresql://localhost:15721/smallbank
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  1.0

10:34:36,031 (DBWorkload.java:260) INFO  - ======================================================================
10:34:36,042 (DBWorkload.java:512) INFO  - Creating new SMALLBANK database...
10:34:36,257 (DBWorkload.java:514) INFO  - Finished!
10:34:36,257 (DBWorkload.java:515) INFO  - ======================================================================
10:34:36,257 (DBWorkload.java:538) INFO  - Loading data into SMALLBANK database...
```
It progresses no further than this. When control c'ing the script, further output is:
```
10:58:25,903 (SmallBankLoader.java:123) ERROR - Failed to load data
java.sql.BatchUpdateException: Batch entry 684 INSERT INTO CHECKING VALUES (215684, 40960) was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:131)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" 10:58:25,903 (SmallBankLoader.java:123) ERROR - Failed to load data
java.sql.BatchUpdateException: Batch entry 4,612 INSERT INTO ACCOUNTS VALUES (419612, '0000000000000000000000000000000000000000000000000000000000419612') was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
        at org.postgresql.core.v3.QueryExecutorImpl$1.handleError(QueryExecutorImpl.java:436)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:129)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Failed to execute threads: java.sql.BatchUpdateException: Batch entry 684 INSERT INTO CHECKING VALUES (215684, 40960) was aborted.  Call getNextException to see the cause.
 at com.oltpbenchmark.util.ThreadUtil.run(ThreadUtil.java:309)
        at com.oltpbenchmark.util.ThreadUtil.runNewPool(ThreadUtil.java:275)
        at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:326)
        at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:295)
        at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:799)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:539)
Caused by: java.lang.RuntimeException: java.sql.BatchUpdateException: Batch entry 684 INSERT INTO CHECKING VALUES (215684, 40960) was aborted.  Call getNextException to see the cause.
10:58:25,903 (SmallBankLoader.java:123) ERROR - Failed to load data
java.sql.BatchUpdateException: Batch entry 1,900 INSERT INTO SAVINGS VALUES (316900, 13901) was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:130)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:124)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.BatchUpdateException: Batch entry 684 INSERT INTO CHECKING VALUES (215684, 40960) was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:131)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
        ... 5 more
10:58:25,903 (SmallBankLoader.java:123) ERROR - Failed to load data
java.sql.BatchUpdateException: Batch entry 4,501 INSERT INTO SAVINGS VALUES (519501, 28294) was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:130)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
10:58:25,903 (SmallBankLoader.java:123) ERROR - Failed to load data
java.sql.BatchUpdateException: Batch entry 1,678 INSERT INTO CHECKING VALUES (116678, 44032) was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:131)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
10:58:25,903 (SmallBankLoader.java:123) ERROR - Failed to load data
java.sql.BatchUpdateException: Batch entry 4,000 INSERT INTO CHECKING VALUES (714000, 16968) was aborted.  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:131)
        at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Configuration file attached. 
[smallbank_config.xml.txt](https://github.com/cmu-db/peloton/files/1619542/smallbank_config.xml.txt)

Ran on:
- Ubuntu 14.04 LTS
- Peloton debug build

**Comment by pervazea** [comment]
Apart from #1269, the benchmark now runs.
