### ISSUE TITLE
OLTPBench: Voter Benchmark Fails

### ISSUE THREAD

**Issue by schedutron** [cmu-db/peloton#1080]
I get the following `oltpbenchmark` logs when benchmarking the voter database:

```
oltpbench $ ./oltpbenchmark -b voter -c config/sample_voter_config.xml --create=true --load=true --execute=true 
22:37:14,400 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     VOTER {com.oltpbenchmark.benchmarks.voter.VoterBenchmark}
Configuration: config/sample_voter_config.xml
Type:          PELOTON
Driver:        org.postgresql.Driver
URL:           jdbc:postgresql://localhost:15721/voter
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  10.0

22:37:14,402 (DBWorkload.java:260) INFO  - ======================================================================
22:37:14,411 (DBWorkload.java:519) INFO  - Creating new VOTER database...
Error executing: CREATE VIEW V_VOTES_BY_PHONE_NUMBER (   phone_number , num_votes ) AS    SELECT phone_number         , COUNT(*)      FROM VOTES  GROUP BY phone_number  
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to create the voter database
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:268)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:248)
	at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:801)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:520)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:796)
	at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:753)
	at com.oltpbenchmark.util.ScriptRunner.runScript(ScriptRunner.java:104)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:266)
	... 3 more
```

Here are server logs:

```
oltpbench $ peloton
2018-01-20 22:37:10 [src/network/network_manager.cpp:49:CreateNewConnection] INFO  - Create new connection: id = 4
2018-01-20 22:37:10 [src/network/network_manager.cpp:167:StartServer] INFO  - Listening on port 15721
2018-01-20 22:37:14 [src/network/network_master_thread.cpp:129:DispatchConnection] DEBUG - Dispatching connection to worker 0
2018-01-20 22:37:14 [src/network/network_callback_util.cpp:45:WorkerHandleNewConn] DEBUG - Creating new socket fd:17
2018-01-20 22:37:14 [src/network/network_manager.cpp:49:CreateNewConnection] INFO  - Create new connection: id = 17
2018-01-20 22:37:14 [src/network/network_connection.cpp:425:ProcessInitialPacket] INFO  - protocol version: 196608
2018-01-20 22:37:14 [src/planner/create_plan.cpp:186:CreatePlan] ERROR - UNKNOWN CREATE TYPE
libc++abi.dylib: terminating with uncaught exception of type peloton::CatalogException: Can't find Database  to create table
Abort trap: 6
```

**Comment by pervazea** [comment]
If I remember correctly, we used to ignore the database specified in the connection string. This is no longer true. Replace "voter" with "default_database" along with the other necessary adjustments to the sample file.

I believe we don't support views, so you'll get past this, but fail later.
