### ISSUE TITLE
Unable to connect to Peloton server

### ISSUE THREAD

**Issue by schedutron** [cmu-db/peloton#1141]
I try to connect to Peloton server with the command `psql "sslmode=disable" -h localhost -p 15721`, but the connection fails and I get the following logs on the server side:

```
$ peloton 
2018-02-11 00:31:19 [src/network/peloton_server.cpp:128:SSLInit] ERROR - Exception when loading root_crt!
2018-02-11 00:31:19 [src/network/peloton_server.cpp:137:SSLInit] INFO  - certificate file path /Users/binaryboy/Desktop/peloton/data/server.crt
2018-02-11 00:31:19 [src/network/peloton_server.cpp:140:SSLInit] ERROR - Exception when loading server certificate!
2018-02-11 00:31:19 [src/network/peloton_server.cpp:267:SetupServer] INFO  - Listening on port 15721
2018-02-11 00:32:11 [src/network/connection_dispatcher_task.cpp:63:DispatchConnection] DEBUG - Dispatching connection to worker 0
=================================================================
==5707==ERROR: AddressSanitizer: container-overflow on address 0x62500003e900 at pc 0x00010f967bc8 bp 0x700000f29cd0 sp 0x700000f29480
WRITE of size 86 at 0x62500003e900 thread T7
    #0 0x10f967bc7 in wrap_read (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1dbc7)
    #1 0x10bfc7b37 in peloton::network::ConnectionHandle::FillReadBuffer() connection_handle.cpp:292
    #2 0x10bfcc068 in peloton::network::ConnectionHandle::StateMachine::Delta_(peloton::network::ConnState, peloton::network::Transition)::$_0::operator()(peloton::network::ConnectionHandle&) const connection_handle.cpp:90
    #3 0x10bfcc047 in peloton::network::ConnectionHandle::StateMachine::Delta_(peloton::network::ConnState, peloton::network::Transition)::$_0::__invoke(peloton::network::ConnectionHandle&) connection_handle.cpp:90
    #4 0x10bfbc1ab in peloton::network::ConnectionHandle::StateMachine::Accept(peloton::network::Transition, peloton::network::ConnectionHandle&) connection_handle.cpp:122
    #5 0x10bfcd84a in peloton::network::ConnectionHandle::HandleEvent(int, short) connection_handle.h:71
    #6 0x10bfcd7fc in peloton::network::ConnectionHandle::ConnectionHandle(int, peloton::network::ConnectionHandlerTask*, std::__1::shared_ptr<peloton::network::Buffer>, std::__1::shared_ptr<peloton::network::Buffer>, bool)::$_13::operator()(int, short, void*) const connection_handle.cpp:145
    #7 0x10bfcd7c7 in peloton::network::ConnectionHandle::ConnectionHandle(int, peloton::network::ConnectionHandlerTask*, std::__1::shared_ptr<peloton::network::Buffer>, std::__1::shared_ptr<peloton::network::Buffer>, bool)::$_13::__invoke(int, short, void*) connection_handle.cpp:145
    #8 0x10f3f19c1 in event_process_active_single_queue (libevent-2.1.6.dylib:x86_64+0x109c1)
    #9 0x10f3eecb2 in event_base_loop (libevent-2.1.6.dylib:x86_64+0xdcb2)
    #10 0x10bfb9434 in peloton::network::EventUtil::EventBaseDispatch(event_base*) error_util.h:85
    #11 0x10bfb9409 in peloton::network::NotifiableTask::EventLoop() notifiable_task.h:216
    #12 0x10bfb93b0 in peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2::operator()() const connection_dispatcher_task.cpp:43
    #13 0x10bfb8b97 in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2> >(void*, void*) type_traits:4291
    #14 0x7fff6d2a96c0 in _pthread_body (libsystem_pthread.dylib:x86_64+0x36c0)
    #15 0x7fff6d2a956c in _pthread_start (libsystem_pthread.dylib:x86_64+0x356c)
    #16 0x7fff6d2a8c5c in thread_start (libsystem_pthread.dylib:x86_64+0x2c5c)

0x62500003e900 is located 0 bytes inside of 8192-byte region [0x62500003e900,0x625000040900)
allocated by thread T7 here:
    #0 0x10f9a2e9c in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x58e9c)
    #1 0x10b706e7c in peloton::do_allocation(unsigned long, bool) allocator.cpp:29
    #2 0x10b706f29 in operator new(unsigned long) allocator.cpp:42
    #3 0x10bad36d5 in std::__1::__split_buffer<unsigned char, std::__1::allocator<unsigned char>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<unsigned char>&) new:226
    #4 0x10bad0d1c in std::__1::__split_buffer<unsigned char, std::__1::allocator<unsigned char>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<unsigned char>&) __split_buffer:310
    #5 0x10bfd9e17 in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::reserve(unsigned long) vector:1533
    #6 0x10bfe5fb7 in peloton::network::Buffer::Buffer() marshal.h:36
    #7 0x10bfe5ba4 in peloton::network::Buffer::Buffer() marshal.h:34
    #8 0x10bfe4f56 in std::__1::shared_ptr<peloton::network::Buffer> std::__1::shared_ptr<peloton::network::Buffer>::make_shared<>() memory:2156
    #9 0x10bfdd902 in peloton::network::ConnectionHandleFactory::GetConnectionHandle(int, peloton::network::ConnectionHandlerTask*) memory:4810
    #10 0x10bfdc528 in peloton::network::ConnectionHandlerTask::HandleDispatch(int, short) connection_handler_task.cpp:58
    #11 0x10bfdf73c in peloton::network::ConnectionHandlerTask::ConnectionHandlerTask(int)::$_0::operator()(int, short, void*) const connection_handler_task.cpp:29
    #12 0x10bfdf707 in peloton::network::ConnectionHandlerTask::ConnectionHandlerTask(int)::$_0::__invoke(int, short, void*) connection_handler_task.cpp:29
    #13 0x10f3f19c1 in event_process_active_single_queue (libevent-2.1.6.dylib:x86_64+0x109c1)
    #14 0x10f3eecb2 in event_base_loop (libevent-2.1.6.dylib:x86_64+0xdcb2)
    #15 0x10bfb9434 in peloton::network::EventUtil::EventBaseDispatch(event_base*) error_util.h:85
    #16 0x10bfb9409 in peloton::network::NotifiableTask::EventLoop() notifiable_task.h:216
    #17 0x10bfb93b0 in peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2::operator()() const connection_dispatcher_task.cpp:43
    #18 0x10bfb8b97 in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2> >(void*, void*) type_traits:4291
    #19 0x7fff6d2a96c0 in _pthread_body (libsystem_pthread.dylib:x86_64+0x36c0)
    #20 0x7fff6d2a956c in _pthread_start (libsystem_pthread.dylib:x86_64+0x356c)
    #21 0x7fff6d2a8c5c in thread_start (libsystem_pthread.dylib:x86_64+0x2c5c)

Thread T7 created by T0 here:
    #0 0x10f99a676 in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x50676)
    #1 0x10bfb7cca in std::__1::thread::thread<peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2&, void>(peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2&&&) __threading_support:310
    #2 0x10bfb6f2c in std::__1::thread::thread<peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2&, void>(peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int)::$_2&&&) thread:354
    #3 0x10bfa9a1f in _ZN7peloton10ThreadPool19SubmitDedicatedTaskIZNS_7network24ConnectionDispatcherTaskC1EiiE3$_2JEEEvOT_DpOKT0_ thread_pool.h:76
    #4 0x10bfa5833 in peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int) connection_dispatcher_task.cpp:43
    #5 0x10bfaa740 in peloton::network::ConnectionDispatcherTask::ConnectionDispatcherTask(int, int) connection_dispatcher_task.cpp:22
    #6 0x10c00b59f in std::__1::shared_ptr<peloton::network::ConnectionDispatcherTask> std::__1::shared_ptr<peloton::network::ConnectionDispatcherTask>::make_shared<unsigned long&, int&>(unsigned long&&&, int&&&) memory:2172
    #7 0x10c007ebb in peloton::network::PelotonServer::SetupServer() memory:4810
    #8 0x10af6aa76 in main peloton.cpp:53
    #9 0x7fff6d01e114 in start (libdyld.dylib:x86_64+0x1114)

HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1dbc7) in wrap_read
Shadow bytes around the buggy address:
  0x1c4a00007cd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c4a00007ce0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c4a00007cf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c4a00007d00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c4a00007d10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x1c4a00007d20:[fc]fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x1c4a00007d30: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x1c4a00007d40: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x1c4a00007d50: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x1c4a00007d60: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
  0x1c4a00007d70: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==5707==ABORTING
Abort trap: 6
```

**Comment by schedutron** [comment]
I'm attaching few screenshots since the above dump is (relatively) less readable:

<img width="1280" alt="screen shot 2018-02-11 at 12 35 37 am" src="https://user-images.githubusercontent.com/22810216/36065659-cf6b117a-0ec3-11e8-95d7-57fee3528a6d.png">
<img width="1280" alt="screen shot 2018-02-11 at 12 35 59 am" src="https://user-images.githubusercontent.com/22810216/36065665-da5a3c1e-0ec3-11e8-9821-4bf98defc774.png">
<img width="1280" alt="screen shot 2018-02-11 at 12 36 20 am" src="https://user-images.githubusercontent.com/22810216/36065669-eb2e223a-0ec3-11e8-8c87-9cb669a043f1.png">

**Comment by dasdipanjan04** [comment]
I was about to create the same issue. Happened with me too. @schedutron thanks for creating this issue.

**Comment by schedutron** [comment]
Maybe this presentation will be useful to fix this: https://llvm.org/devmtg/2014-04/PDFs/LightningTalks/EuroLLVM%202014%20--%20container%20overflow.pdf
