### ISSUE TITLE
Inconsistent insert value type and insert_plan field type

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1197]
Overview;
When trying to run oltpbench TPCC benchmark against the current master, Peloton segfaults and the benchmark fails. At the point of failure, the database has been loaded and we are in the execution / measurement phase.

terminate called after throwing an instance of 'peloton::Exception'
  what():  TIMESTAMP is not coercable to DECIMAL

Partial stack trace at point of failure is:
```
#0  peloton::type::TimestampType::CastAs (this=0x432c40, val=...,
    type_id=peloton::type::TypeId::DECIMAL)
    at /home/pakhtar/proj/pa/peloton/src/type/timestamp_type.cpp:166
#1  0x00007ffff64e1fd2 in peloton::type::Value::CastAs (this=0x7fff6403cb80,
    type_id=peloton::type::TypeId::DECIMAL)
    at /home/pakhtar/proj/pa/peloton/src/include/type/value.h:261
#2  0x00007ffff674ff6a in peloton::planner::InsertPlan::SetParameterValues (
    this=0x7fff6403d300, values=0x7fffc6b8b7b0)
    at /home/pakhtar/proj/pa/peloton/src/planner/insert_plan.cpp:125
#3  0x00007ffff64dd92c in peloton::network::PostgresProtocolHandler::ExecBindMessage (this=0x7fff64002830, pkt=0x7fff64002858)
    at /home/pakhtar/proj/pa/peloton/src/network/postgres_protocol_handler.cpp:600
#4  0x00007ffff64e164e in peloton::network::PostgresProtocolHandler::ProcessPacket (this=0x7fff64002830, pkt=0x7fff64002858, thread_id=4)
    at /home/pakhtar/proj/pa/peloton/src/network/postgres_protocol_handler.cpp:1176
#5  0x00007ffff64e1593 in peloton::network::PostgresProtocolHandler::Process (
    this=0x7fff64002830, rbuf=..., thread_id=4)
    at /home/pakhtar/proj/pa/peloton/src/network/postgres_protocol_handler.cpp:1147
```

The table of interest is:
```
CREATE TABLE oorder (
  o_w_id int NOT NULL PRIMARY KEY,
  o_d_id int NOT NULL PRIMARY KEY,
  o_id int NOT NULL PRIMARY KEY,
  o_c_id int NOT NULL,
  o_carrier_id int,
  o_ol_cnt decimal NOT NULL,
  o_all_local decimal NOT NULL,
  o_entry_d timestamp NOT NULL
```
Previously, we have executed:
PrepareStatement[S_7] => INSERT INTO OORDER VALUES ($1, $2, $3, $4, $5, $6, $7, $8). This may be irrelevant.

but the current operation is:
INFO  - PrepareStatement[] => INSERT INTO OORDER (O_ID, O_D_ID, O_W_ID, O_C_ID, O_ENTRY_D, O_OL_CNT, O_ALL_LOCAL) VALUES ($1, $2, $3, $4, $5, $6, $7)

The failure occurs on entry O_ENTRY_D, which is item 4 (starting with 0) in the above insert, but 6 in the params_value_type_ vector

params_value_type_ from the insert plan, is:
std::vector of length 7, capacity 8 = {
  peloton::type::TypeId::INTEGER,
  peloton::type::TypeId::INTEGER,
  peloton::type::TypeId::INTEGER,
  peloton::type::TypeId::INTEGER, 
  peloton::type::TypeId::DECIMAL,
  peloton::type::TypeId::DECIMAL, 
  peloton::type::TypeId::TIMESTAMP

Environment:
Ubuntu 16.04, laptop, 8 cores, 
g++ 5.4.0

**Comment by pervazea** [comment]
Fixed by #1237.
