### ISSUE TITLE
Jenkins build / checkout failure

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1295]
This is from PR-1278 (which is mine)

We have seen this possibly 3 times in the past week, on different PRs. It seems to require additional pushes to be done to the PR to get past this. 

```
hudson.plugins.git.GitException: Command "git checkout -f 2fc7e14cba60d473c06325e4c8501d9e81b62cf7" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 2fc7e14cba60d473c06325e4c8501d9e81b62cf7

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2295)
Caused: hudson.plugins.git.GitException: Could not checkout 2fc7e14cba60d473c06325e4c8501d9e81b62cf7
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2319)
	at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:146)
	at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:112)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1068)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1161)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:143)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:120)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:295)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

**Comment by crd477** [comment]
This was related to just one of the worker nodes that didn't have the correct default network route. I've fixed it.
I suspect this situation cropped up during the recent disk space failures. For that problem, I've installed a cron job to clean up old build workspaces so hopefully it will not appear again.

**Comment by crd477** [comment]
I noticed this happening a few more times since my last comment.  Upon further investigation, the cause was invalid DHCP and metadata being served by a staging system I had on the same network.  I've stopped the offending services on that system and I'm confident this particular problem of the worker nodes not being able to access github will not happen again.  Sorry for the hassle...
