### ISSUE TITLE
insert into select statement does not work

### ISSUE THREAD

**Issue by shlee0605** [cmu-db/peloton#136]
After running the following statements, I get the segmentation fault error.

```
create table a(test int);
create table b(test int);

insert into a values(1);
insert into a values(2);

insert into b select * from a;
```

I also attach the stack trace and logs.
It seems that peloton supports the regular insert statements only.

```
20:28:37,957 [../../src/backend/bridge/dml/mapper/dml_utils.cpp:197:PrepareModifyTableState] INFO  - CMD_INSERT
20:28:37,957 [../../src/backend/bridge/dml/mapper/dml_utils.cpp:247:PrepareInsertState] ERROR - Unsupported child type of Insert: 109
20:28:37,957 [../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:39:TransformModifyTable] INFO  - CMD_INSERT
20:28:37,957 [../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:84:TransformInsert] INFO  - Insert into: database oid 12111 table oid 298832: c

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffea8f4700 (LWP 27224)]
0x00007ffff6d45c7b in peloton::bridge::PlanTransformer::TransformInsert (mt_plan_state=0x7fffdc1487c0, options=...) at ../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:86
86        AbstractPlanState *sub_planstate = mt_plan_state->mt_plans[0];
(gdb) where
#0  0x00007ffff6d45c7b in peloton::bridge::PlanTransformer::TransformInsert (mt_plan_state=0x7fffdc1487c0, options=...) at ../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:86
#1  0x00007ffff6d4599e in peloton::bridge::PlanTransformer::TransformModifyTable (mt_plan_state=0x7fffdc1487c0, options=...) at ../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:40
#2  0x00007ffff6d438ae in peloton::bridge::PlanTransformer::TransformPlan (planstate=0x7fffdc1487c0, options=...) at ../../src/backend/bridge/dml/mapper/mapper.cpp:88
#3  0x00007ffff6d43725 in peloton::bridge::PlanTransformer::TransformPlan (this=0x7fffea8edda0, planstate=0x7fffdc1487c0, prepStmtName=0x0) at ../../src/backend/bridge/dml/mapper/mapper.cpp:62
#4  0x00007ffff7779030 in peloton_dml (planstate=0x7fffdc147af0, sendTuples=false, dest=0x7fffdc13d890, tuple_desc=0x7fffdc1485e0, prepStmtName=0x0) at ../../src/postgres/backend/postmaster/peloton.cpp:192
#5  0x00007ffff7620823 in peloton_ExecutePlan (estate=0x7fffdc1478a0, planstate=0x7fffdc147af0, operation=CMD_INSERT, sendTuples=false, numberTuples=0, direction=ForwardScanDirection, dest=0x7fffdc13d890, tupDesc=0x7fffdc1485e0, prepStmtName=0x0) at ../../src/postgres/backend/executor/execMain.cpp:1658
#6  0x00007ffff761e953 in standard_ExecutorRun (queryDesc=0x7fffdc141880, direction=ForwardScanDirection, count=0) at ../../src/postgres/backend/executor/execMain.cpp:378
#7  0x00007ffff761e7c1 in ExecutorRun (queryDesc=0x7fffdc141880, direction=ForwardScanDirection, count=0) at ../../src/postgres/backend/executor/execMain.cpp:300
#8  0x00007ffff7807e65 in ProcessQuery (plan=0x7fffdc141208, sourceText=0x7fffdc068130 "insert into c\nselect * from a;", params=0x0, dest=0x7fffdc13d890, completionTag=0x7fffea8ed0e0 "", prepStmtName=0x0) at ../../src/postgres/backend/tcop/pquery.cpp:164
#9  0x00007ffff7809854 in PortalRunMulti (portal=0x7fffdc143880, isTopLevel=true, dest=0x7fffdc13d890, altdest=0x7fffdc13d890, completionTag=0x7fffea8ed0e0 "") at ../../src/postgres/backend/tcop/pquery.cpp:1158
#10 0x00007ffff7808d68 in PortalRun (portal=0x7fffdc143880, count=9223372036854775807, isTopLevel=true, dest=0x7fffdc13d890, altdest=0x7fffdc13d890, completionTag=0x7fffea8ed0e0 "") at ../../src/postgres/backend/tcop/pquery.cpp:739
#11 0x00007ffff78023f6 in exec_simple_query (query_string=0x7fffdc068130 "insert into c\nselect * from a;") at ../../src/postgres/backend/tcop/postgres.cpp:1118
#12 0x00007ffff7806d4c in PostgresMain (argc=1, argv=0x7fffdc001f88, dbname=0x7fffdc000c78 "postgres", username=0x7fffdc000c10 "vagrant") at ../../src/postgres/backend/tcop/postgres.cpp:4054
#13 0x00007ffff778bf22 in BackendRun (port=0x60df70) at ../../src/postgres/backend/postmaster/postmaster.cpp:4015
#14 0x00007ffff778b2dd in BackendTask (bn=0x60e130, port=0x60df70, param=0x62ef60) at ../../src/postgres/backend/postmaster/postmaster.cpp:3634
#15 0x00007ffff779032a in std::_Bind_simple<void (*(bkend*, Port*, BackendParameters*))(bkend*, Port*, BackendParameters*)>::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x614300) at /usr/include/c++/4.8/functional:1732
#16 0x00007ffff779014b in std::_Bind_simple<void (*(bkend*, Port*, BackendParameters*))(bkend*, Port*, BackendParameters*)>::operator()() (this=0x614300) at /usr/include/c++/4.8/functional:1720
#17 0x00007ffff779009a in std::thread::_Impl<std::_Bind_simple<void (*(bkend*, Port*, BackendParameters*))(bkend*, Port*, BackendParameters*)> >::_M_run() (this=0x6142e8) at /usr/include/c++/4.8/thread:115
#18 0x00007ffff560da60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007ffff4be6182 in start_thread (arg=0x7fffea8f4700) at pthread_create.c:312
#20 0x00007ffff629c47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by shlee0605** [comment]
The following query, which is used for the similar usage, is also not working.
```
create table b as select * from a;
```

**Comment by apavlo** [comment]
We definitely don't support these type of queries yet. Is there a specific reason that you need this or can you work around it for now?

**Comment by shlee0605** [comment]
@apavlo Iterative machine learning algorithms usually store intermediate data to temporary tables. Our team initially planned to show some ml udf functions (e.g. pagerank) for the demo.
