### ISSUE TITLE
YCSB fails with the new type-system (SIGSEGV)

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#234]
stacktrace

````
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6d051af in free () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1

0  0x00007ffff6d051af in free () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#1  0x00007ffff786e1b0 in peloton::do_deletion (location=0x4) at /home/siddharth/git/peloton/src/common/allocator.cpp:35
#2  0x00007ffff786e27e in operator delete (location=0x4) at /home/siddharth/git/peloton/src/common/allocator.cpp:56
#3  0x00007ffff778071e in __gnu_cxx::new_allocator<peloton::expression::AbstractExpression*>::deallocate (this=0x7fffe9de44a0, __p=0x4) at /usr/include/c++/4.8/ext/new_allocator.h:110
#4  0x00007ffff778030c in std::_Vector_base<peloton::expression::AbstractExpression*, std::allocator<peloton::expression::AbstractExpression*> >::_M_deallocate (this=0x7fffe9de44a0, __p=0x4, __n=17592186044415) at /usr/include/c++/4.8/bits/stl_vector.h:174
#5  0x00007ffff777fec3 in std::_Vector_base<peloton::expression::AbstractExpression*, std::allocator<peloton::expression::AbstractExpression*> >::~_Vector_base (this=0x7fffe9de44a0, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:160
#6  0x00007ffff777f919 in std::vector<peloton::expression::AbstractExpression*, std::allocator<peloton::expression::AbstractExpression*> >::~vector (this=0x7fffe9de44a0, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:416
#7  0x00007ffff794de0d in peloton::parser::InsertStatement::~InsertStatement (this=0x7ffff1d01310, __in_chrg=<optimized out>) at /home/siddharth/git/peloton/src/include/parser/statement_insert.h:48
#8  0x00007ffff794de82 in peloton::parser::InsertStatement::~InsertStatement (this=0x7ffff1d01310, __in_chrg=<optimized out>) at /home/siddharth/git/peloton/src/include/parser/statement_insert.h:52
#9  0x00007ffff794cf7f in peloton::parser::SQLStatementList::~SQLStatementList (this=0x7ffff1c16680, __in_chrg=<optimized out>) at /home/siddharth/git/peloton/src/include/parser/sql_statement.h:58
#10 0x00007ffff794cff2 in peloton::parser::SQLStatementList::~SQLStatementList (this=0x7ffff1c16680, __in_chrg=<optimized out>) at /home/siddharth/git/peloton/src/include/parser/sql_statement.h:62
#11 0x00007ffff7772a6a in std::default_delete<peloton::parser::SQLStatementList>::operator() (this=0x7ffff2bfb390, __ptr=0x7ffff1c16680) at /usr/include/c++/4.8/bits/unique_ptr.h:67
#12 0x00007ffff7772889 in std::unique_ptr<peloton::parser::SQLStatementList, std::default_delete<peloton::parser::SQLStatementList> >::~unique_ptr (this=0x7ffff2bfb390, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/unique_ptr.h:184
#13 0x00007ffff792b251 in peloton::tcop::TrafficCop::PrepareStatement (this=0x7ffff7dd9ae8 <peloton::tcop::TrafficCop::GetInstance()::traffic_cop>, statement_name="", query_string="INSERT INTO \"USERTABLE\" VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)", error_message="") at /home/siddharth/git/peloton/src/tcop/tcop.cpp:105
#14 0x00007ffff78a2cc1 in peloton::wire::PacketManager::ExecParseMessage (this=0x7ffff44488c0, pkt=0x7ffff2bfb5f0, responses=std::vector of length 0, capacity 2) at /home/siddharth/git/peloton/src/networking/protocol.cpp:306
#15 0x00007ffff78a56bc in peloton::wire::PacketManager::ProcessPacket (this=0x7ffff44488c0, pkt=0x7ffff2bfb5f0, responses=std::vector of length 0, capacity 2) at /home/siddharth/git/peloton/src/networking/protocol.cpp:603
#16 0x00007ffff78a5b49 in peloton::wire::PacketManager::ManagePacket (this=0x7ffff44488c0) at /home/siddharth/git/peloton/src/networking/protocol.cpp:697
#17 0x00007ffff7908d19 in peloton::wire::ManageRead (socket_manager=0x7ffff4469038) at /home/siddharth/git/peloton/src/wire/libevent_server.cpp:63
#18 0x00007ffff790bf26 in std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x7ffff2bfb7c0, __args=<unknown type in /home/siddharth/git/peloton/build/lib/libpeloton-d.so.0.0.3, CU 0x12027e1, DIE 0x12354f7>) at /usr/include/c++/4.8/functional:1296
#19 0x00007ffff790be70 in std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>::operator()<, void>() (this=0x7ffff2bfb7c0) at /usr/include/c++/4.8/functional:1355
#20 0x00007ffff790bdd4 in boost::asio::asio_handler_invoke<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >(std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#21 0x00007ffff790bd24 in boost_asio_handler_invoke_helpers::invoke<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>, std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >(std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>&, std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>&) (function=..., context=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#22 0x00007ffff790bc03 in boost::asio::detail::completion_handler<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x7ffff4410240, base=0x7ffff1c13550) at /usr/include/boost/asio/detail/completion_handler.hpp:68
#23 0x00007ffff788d0a8 in boost::asio::detail::task_io_service_operation::complete (this=0x7ffff1c13550, owner=..., ec=..., bytes_transferred=0) at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#24 0x00007ffff788df3d in boost::asio::detail::task_io_service::do_run_one (this=0x7ffff4410240, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:384
#25 0x00007ffff788dc79 in boost::asio::detail::task_io_service::run (this=0x7ffff4410240, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#26 0x00007ffff788e2d7 in boost::asio::io_service::run (this=0x7ffff7dd9500 <peloton::thread_pool+352>) at /usr/include/boost/asio/impl/io_service.ipp:59
#27 0x00007ffff7898579 in boost::_mfi::mf0<unsigned long, boost::asio::io_service>::operator() (this=0x7ffff4415bb8, p=0x7ffff7dd9500 <peloton::thread_pool+352>) at /usr/include/boost/bind/mem_fn_template.hpp:49
#28 0x00007ffff78984dd in boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list0> (this=0x7ffff4415bc8, f=..., a=...) at /usr/include/boost/bind/bind.hpp:243
#29 0x00007ffff7898163 in boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >::operator() (this=0x7ffff4415bb8) at /usr/include/boost/bind/bind_template.hpp:20
#30 0x00007ffff7897db0 in boost::detail::thread_data<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >::run (this=0x7ffff4415a00) at /usr/include/boost/thread/detail/thread.hpp:117
#31 0x00007ffff66dca4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#32 0x00007ffff64bb184 in start_thread (arg=0x7ffff2bfc700) at pthread_create.c:312
#33 0x00007ffff526237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
````

**Comment by MattPerron** [comment]
Is this a transient issue or do you have a set of conditions to reproduce it?

**Comment by sid1607** [comment]
```
./oltpbenchmark -b ycsb -c config/peloton_ycsb_config.xml --create=true --load=true --execute=true -s 5 -o outputfile --histograms
```
This appears everytime after loading table completes.

**Comment by MattPerron** [comment]
As we said in today's meeting, this is now working.
