### ISSUE TITLE
Large Sequential Scans with high selectivity cause JDBC to break 

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#397]
When I populate a table with 10million tuples using a JDBC client and run a 10% selectivity query, the client crashes while Peloton is writing the output.

Peloton-side output
--------------------------
[ERROR] [src/wire/libevent_socket.cpp:349:FlushWriteBuffer()] 2016-12-14 15:29:27 - Fatal error during write
[ERROR] [src/wire/libevent_callbacks.cpp:187:StateMachine()] 2016-12-14 15:29:27 - Error during write, closing connection

JDBC-side output
-----------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ExchangeTest.TimeAndExecuteQuery(ExchangeTest.java:378)
	at ExchangeTest.main(ExchangeTest.java:463)
Caused by: java.lang.NegativeArraySizeException
	at org.postgresql.core.PGStream.ReceiveTupleV3(PGStream.java:369)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1986)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:159)
	at ExchangeTest.Selectivity10Scan(ExchangeTest.java:301)
	... 6 more

The bug is likely to be in the wire protocol implementation for writing responses.

**Comment by sid1607** [comment]
The reason this issue happens is that the response payload is too large to be delivered by the standard wire protocol. Based on the discussion in this link - http://stackoverflow.com/questions/31904559/32bit-message-length-1gb-query it looks like Postgres wire protocol isn't designed to send more than 1GB of payload in a single packet. The wire protocol has the "Copy operations" feature that enables bulk data transfer. @eric-haibin-lin  is the wire Copy operation related to the CopyExecutor that you implemented?
