### ISSUE TITLE
Inconsistent results with basic1.sql

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#401]
This is a weird one. I'm still working through things to figure out what's going on here. The [psql_test.sh](https://github.com/cmu-db/peloton/blob/master/script/testing/psql/psql_test.sh) invokes [basic1.sql](https://github.com/cmu-db/peloton/blob/master/script/testing/dml/basic1.sql). Right now it works on my laptop, but if you invoke it in different environments I get different results

### Jenkins
The test fails when it runs inside of a Jenkins build because the resulting output doesn't match our expected output:
```
bash ../script/testing/psql/psql_test.sh
Exception Type :: Catalog
Message :: Table 'foo' does not exist
Exception Type :: Catalog
Message :: Table 'foo' does not exist
Exception Type :: Catalog
Message :: Table 'foo' does not exist
***FAIL***
68c68
< UPDATE foo SET id= 10 WHERE year = 1000 2
---
> UPDATE foo SET id= 10 WHERE year = 1000 1
```

### Jenkins (command-line)
When I run it on our jenkins box from the command-line, we get a segfault:
```
$ ../script/testing/psql/psql_test.sh 
Exception Type :: Catalog
Message :: Table 'foo' does not exist
Exception Type :: Catalog
Message :: Table 'foo' does not exist
Exception Type :: Catalog
Message :: Table 'foo' does not exist
../script/testing/psql/psql_test.sh: line 53: 45493 Segmentation fault
      (core dumped) bin/peloton -port $PELOTON_PORT > /dev/null
```

Here is the stack trace when run it through gdb:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe9bff700 (LWP 45337)]
0x00007ffff59c845b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff59c845b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff778c015 in peloton::expression::TupleValueExpression::GetColumnName (this=0x7fffe347b240)
    at /home/pavlo/Documents/Peloton/Github/peloton/src/include/expression/tuple_value_expression.h:87
#2  0x00007ffff78c2fa5 in peloton::optimizer::SimpleOptimizer::BuildPelotonPlanTree (parse_tree=std::unique_ptr<peloton::parser::SQLStatementList> containing 0x7fffe3430180)
    at /home/pavlo/Documents/Peloton/Github/peloton/src/optimizer/simple_optimizer.cpp:278
#3  0x00007ffff76e56a0 in peloton::tcop::TrafficCop::PrepareStatement (this=0x7ffff7dd63e8 <peloton::tcop::TrafficCop::GetInstance()::traffic_cop>, statement_name="unnamed", 
    query_string="select * from foo order by id", error_message="") at /home/pavlo/Documents/Peloton/Github/peloton/src/tcop/tcop.cpp:131
#4  0x00007ffff76e5008 in peloton::tcop::TrafficCop::ExecuteStatement (this=0x7ffff7dd63e8 <peloton::tcop::TrafficCop::GetInstance()::traffic_cop>, 
    query="select * from foo order by id", result=std::vector of length 0, capacity 0, tuple_descriptor=std::vector of length 0, capacity 0, 
    rows_changed=@0x7fffe9bfe874: 32767, error_message="") at /home/pavlo/Documents/Peloton/Github/peloton/src/tcop/tcop.cpp:61
#5  0x00007ffff767a712 in peloton::wire::PacketManager::ExecQueryMessage (this=0x7fffe340f0a0, pkt=0x7fffe340f240)
    at /home/pavlo/Documents/Peloton/Github/peloton/src/networking/protocol.cpp:248
#6  0x00007ffff767e5a7 in peloton::wire::PacketManager::ProcessPacket (this=0x7fffe340f0a0, pkt=0x7fffe340f240)
    at /home/pavlo/Documents/Peloton/Github/peloton/src/networking/protocol.cpp:737
#7  0x00007ffff7744ae9 in peloton::wire::StateMachine (conn=0x7fffe340f080) at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_callbacks.cpp:155
#8  0x00007ffff7744725 in peloton::wire::EventHandler (connfd=67, ev_flags=2, arg=0x7fffe340f080)
    at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_callbacks.cpp:72
#9  0x00007ffff5c1ef24 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#10 0x00007ffff773d38f in peloton::wire::LibeventMasterThread::StartWorker (worker_thread=0x7fffe9ce8300)
    at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_thread.cpp:57
#11 0x00007ffff7744288 in std::_Bind_simple<void (*(peloton::wire::LibeventWorkerThread*))(peloton::wire::LibeventWorkerThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (
    this=0x7ffff442c870) at /usr/include/c++/4.8/functional:1732
<SNIP>
````

You can easily recreate this by piping `basic1.sql` into psql:
``` 
$ psql "sslmode=disable" -U postgres -h localhost -p 15721 < ./script/testing/dml/basic1.sql  
```

### Jenkins (psql direct)
Now here is where things get really weird. If you connect to the DBMS through psql and then paste the contents of `basic1.sql` into the terminal, everything works fine.

```
$ psql "sslmode=disable" -U postgres -h localhost -p 15721 
psql (9.3.14, server 9.5devel)
WARNING: psql major version 9.3, server major version 9.5.
         Some psql features might not work.
Type "help" for help.

postgres=# -- WARNING: DO NOT MODIFY THIS FILE
postgres=# -- psql tests use the exact output FROM this file for CI
postgres=# 
postgres=# -- create the table
postgres=# -- 2 columns, 1 primary key
postgres=# 
postgres=# DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS foo 0
postgres=# CREATE TABLE foo(id integer PRIMARY KEY, year integer);
CREATE TABLE foo(id integer PRIMARY KEY, year integer) 0
postgres=# -- create index on foo (id); -- failed, why?
postgres=# 
postgres=# -- load in the data
postgres=# 
postgres=# INSERT INTO foo VALUES(1, 100);
INSERT INTO foo VALUES(1, 100) 1
postgres=# INSERT INTO foo VALUES(1, 200); -- should fail
INSERT INTO foo VALUES(1, 200) 0
postgres=# INSERT INTO foo VALUES(2, 200);
INSERT INTO foo VALUES(2, 200) 1
postgres=# INSERT INTO foo VALUES(3, 300);
INSERT INTO foo VALUES(3, 300) 1
postgres=# INSERT INTO foo VALUES(4, 400);
INSERT INTO foo VALUES(4, 400) 1
postgres=# INSERT INTO foo VALUES(5, 400);
INSERT INTO foo VALUES(5, 400) 1
postgres=# INSERT INTO foo VALUES(5, 500); -- should fail
INSERT INTO foo VALUES(5, 500) 0
postgres=# 
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  1 |  100
  2 |  200
  3 |  300
  4 |  400
  5 |  400
(5 rows)

postgres=# 
postgres=# -- SELECT
postgres=# 
postgres=# SELECT id, year FROM foo WHERE id < 3 ORDER BY id;
 id | year 
----+------
  1 |  100
  2 |  200
(2 rows)

postgres=# 
postgres=# SELECT id, year FROM foo WHERE year > 200 ORDER BY id;
 id | year 
----+------
  3 |  300
  4 |  400
  5 |  400
(3 rows)

postgres=# 
postgres=# -- DELETE
postgres=# 
postgres=# DELETE FROM foo WHERE year = 200;
DELETE FROM foo WHERE year = 200 1
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  1 |  100
  3 |  300
  4 |  400
  5 |  400
(4 rows)

postgres=# 
postgres=# 
postgres=# -- -- UPDATE
postgres=# 
postgres=# UPDATE foo SET year = 3000 WHERE id = 3;
UPDATE foo SET year = 3000 WHERE id = 3 1
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  1 |  100
  3 | 3000
  4 |  400
  5 |  400
(4 rows)

postgres=# 
postgres=# UPDATE foo SET year = 1000 WHERE year = 100; 
UPDATE foo SET year = 1000 WHERE year = 100 1
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  1 | 1000
  3 | 3000
  4 |  400
  5 |  400
(4 rows)

postgres=# 
postgres=# UPDATE foo SET id = 3 WHERE year = 1000; -- should fail
UPDATE foo SET id = 3 WHERE year = 1000 1
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  3 | 3000
  3 | 1000
  4 |  400
  5 |  400
(4 rows)

postgres=# 
postgres=# UPDATE foo SET id= 10 WHERE year = 1000;
UPDATE foo SET id= 10 WHERE year = 1000 1
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  3 | 3000
  4 |  400
  5 |  400
 10 | 1000
(4 rows)

postgres=# 
postgres=# -- insert again
postgres=# 
postgres=# INSERT INTO foo VALUES (2, 2000);
INSERT INTO foo VALUES (2, 2000) 1
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  2 | 2000
  3 | 3000
  4 |  400
  5 |  400
 10 | 1000
(5 rows)

postgres=# 
postgres=# INSERT INTO foo VALUES (4, 4000); -- should fail
INSERT INTO foo VALUES (4, 4000) 0
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  2 | 2000
  3 | 3000
  4 |  400
  5 |  400
 10 | 1000
(5 rows)

postgres=# 
postgres=# INSERT INTO foo VALUES (1, 1000);
INSERT INTO foo VALUES (1, 1000) 0
postgres=# SELECT id, year FROM foo ORDER BY id;
 id | year 
----+------
  2 | 2000
  3 | 3000
  4 |  400
  5 |  400
 10 | 1000
(5 rows)

postgres=# 
postgres=# \q
```

**Comment by apavlo** [comment]
I don't think this is an issue for us anymore. Jenkins runs the psql tests.
