### ISSUE TITLE
Network Code Weirdly Crashes Under tmux

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#416]
I am only putting this here in case somebody else hits this. This is on the ottertune machine (Ubuntu 16.04). I am using a clean build from d0f8a851ac275b943a89c80c4955f23683d3897e.

The following the two errors **only** occur when I start the server in tmux. It works just fine from the regular terminal. It also doesn't happen with screen. I have no idea what this could be from and I don't have time to look into it.

Under `DEBUG`, I get a **SEGFAULT** when the system starts:

```
Thread 1 "peloton" received signal SIGSEGV, Segmentation fault.
0x00007ffff764db53 in std::vector<unsigned char, std::allocator<unsigned char> >::~vector (this=0x616e5f7972657859, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/stl_vector.h:424
424           { std::_Destroy(this->_M_impl._M_start, this->_M_impl._M_finish,
(gdb) bt
#0  0x00007ffff764db53 in std::vector<unsigned char, std::allocator<unsigned char> >::~vector (this=0x616e5f7972657859, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/stl_vector.h:424
#1  0x00007ffff764d9c4 in peloton::wire::Buffer::~Buffer (this=0x616e5f7972657841, __in_chrg=<optimized out>) at /home/pavlo/Documents/Peloton/Github/peloton/src/include/wire/libevent_server.h:109
#2  0x00007ffff764edf4 in peloton::wire::LibeventSocket::~LibeventSocket (this=0x616e5f7972657571, __in_chrg=<optimized out>) at /home/pavlo/Documents/Peloton/Github/peloton/src/include/wire/libevent_server.h:155
#3  0x00007ffff764ee4e in std::default_delete<peloton::wire::LibeventSocket>::operator() (this=0x7fffea0c1328, __ptr=0x616e5f7972657571) at /usr/include/c++/5/bits/unique_ptr.h:76
#4  0x00007ffff764e2e1 in std::unique_ptr<peloton::wire::LibeventSocket, std::default_delete<peloton::wire::LibeventSocket> >::reset (this=0x7fffea0c1328, __p=0x616e5f7972657571) at /usr/include/c++/5/bits/unique_ptr.h:344
#5  0x00007ffff764cab1 in peloton::wire::LibeventServer::CreateNewConn (connfd=@0x7fffffffdbf4: 165, ev_flags=18, thread=0x7fffea325380, init_state=peloton::wire::CONN_LISTENING) at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_server.cpp:45
#6  0x00007ffff764cf9c in peloton::wire::LibeventServer::LibeventServer (this=0x7fffffffdd00) at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_server.cpp:118
#7  0x0000000000404283 in main (argc=1, argv=0x7fffffffde38) at /home/pavlo/Documents/Peloton/Github/peloton/src/main/peloton/peloton.cpp:43
```

Under `RELEASE`, I get a **BUS ERROR**:

```
Thread 1 "peloton" received signal SIGBUS, Bus error.
0x00007ffff7955006 in peloton::wire::LibeventServer::CreateNewConn(int const&, short, peloton::wire::LibeventThread*, peloton::wire::ConnState) () from /home/pavlo/Documents/Peloton/Github/peloton/build/lib/libpeloton.so.0.0.3
(gdb) bt
#0  0x00007ffff7955006 in peloton::wire::LibeventServer::CreateNewConn(int const&, short, peloton::wire::LibeventThread*, peloton::wire::ConnState) () from /home/pavlo/Documents/Peloton/Github/peloton/build/lib/libpeloton.so.0.0.3
#1  0x00007ffff79557f9 in peloton::wire::LibeventServer::LibeventServer() () from /home/pavlo/Documents/Peloton/Github/peloton/build/lib/libpeloton.so.0.0.3
#2  0x0000000000402ee5 in main ()
```

@sid1607 Don't worry about this. Focus on the other things.

**Comment by apavlo** [comment]
I should also add that it runs just fine in tmux on my local machine (also 16.04)

**Comment by apavlo** [comment]
I think that @dvanaken's machine is weird. I can't reproduce this on any other machine. I am closing it for now.
