### ISSUE TITLE
PacketManager::Reset() SEGFAULT

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#417]
**I actually think that this machine might have bad DRAM. Let me get back to you on this**
----------------------

The system crashes now when I try to load in a TPC-C database:

```
$ ant build execute -Dbenchmark=tpcc -Dconfig=config/tpcc_config_peloton.xml \
    -Dload=true \
    -Dcreate=true \
    -Dexecute=false
```

This occurs in both `RELEASE` and `DEBUG` compilation modes:

```
Thread 3 "peloton" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe8bff700 (LWP 25008)]
0x00007ffff528796b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::clear() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff528796b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::clear() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff784fa76 in peloton::wire::Client::Reset (this=0x7fffea0c14a8) at /home/pavlo/Documents/Peloton/Github/peloton/src/include/wire/marshal.h:121
#2  0x00007ffff784f382 in peloton::wire::PacketManager::Reset (this=0x7fffea0c14a8) at /home/pavlo/Documents/Peloton/Github/peloton/src/networking/protocol.cpp:811
#3  0x00007ffff7657e44 in peloton::wire::LibeventSocket::Reset (this=0x7fffea0c1488) at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_socket.cpp:503
#4  0x00007ffff76551df in peloton::wire::WorkerHandleNewConn (new_conn_recv_fd=9, ev_flags=2, arg=0x7fffee5cc900) at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_callbacks.cpp:54
#5  0x00007ffff54f7a0c in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#6  0x00007ffff7644493 in peloton::wire::LibeventMasterThread::StartWorker (worker_thread=0x7fffee5cc900) at /home/pavlo/Documents/Peloton/Github/peloton/src/wire/libevent_thread.cpp:57
#7  0x00007ffff764c854 in std::_Bind_simple<void (*(peloton::wire::LibeventWorkerThread*))(peloton::wire::LibeventWorkerThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x7fffebbe0868) at /usr/include/c++/5/functional:1531
#8  0x00007ffff764c440 in std::_Bind_simple<void (*(peloton::wire::LibeventWorkerThread*))(peloton::wire::LibeventWorkerThread*)>::operator()() (this=0x7fffebbe0868) at /usr/include/c++/5/functional:1520
#9  0x00007ffff764c0e6 in std::thread::_Impl<std::_Bind_simple<void (*(peloton::wire::LibeventWorkerThread*))(peloton::wire::LibeventWorkerThread*)> >::_M_run() (this=0x7fffebbe0850) at /usr/include/c++/5/thread:115
#10 0x00007ffff5220c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff5c766fa in start_thread (arg=0x7fffe8bff700) at pthread_create.c:333
#12 0x00007ffff4986b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by sid1607** [comment]
Any updates on this?

**Comment by apavlo** [comment]
I wasn't able to reproduce it on any other machine. We are running memtest now to see whether it has bad DRAM.

**Comment by apavlo** [comment]
I think that @dvanaken's machine is weird. I can't reproduce this on any other machine. I am closing it for now.
