### ISSUE TITLE
JDBC 'ROLLBACK' throws exception for rejected txns

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#436]
I fixed OLTP-Bench so that it doesn't try to rollback a txn twice in TPC-C when there is a `UserAbortException`. The problem is that we don't seem to support JDBC rollback at all:

This line here:

https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/api/Worker.java#L427

Throws this exception:

```
java.lang.RuntimeException: Unexpected fatal, error in 'WORKER<TPCC>010' when executing 'Payment/02' [PELOTON]
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:524)
        at com.oltpbenchmark.api.Worker.run(Worker.java:296)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: 
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
        at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:778)
        at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:811)
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:427)
        ... 2 more
```

This occurs when a Payment txn tries to update the WAREHOUSE table with this query:

https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpcc/procedures/Payment.java#L39

Here is the original exception that causes us to try to rollback the txn:

```
13:19:21,703 (Worker.java:417) WARN  - PSQLException thrown when executing 'Payment/02' on 'WORKER<TPCC>018' [Message='', ErrorCode='0', SQLState='40001']
org.postgresql.util.PSQLException: 
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:137)
        at com.oltpbenchmark.benchmarks.tpcc.procedures.Payment.run(Payment.java:182)
        at com.oltpbenchmark.benchmarks.tpcc.TPCCWorker.executeWork(TPCCWorker.java:74)
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
        at com.oltpbenchmark.api.Worker.run(Worker.java:296)
        at java.lang.Thread.run(Thread.java:745)
```

To reproduce this, run the latest version of OLTP-Bench with an updated version of @jessesleeping's testing scripts:

https://github.com/apavlo/peloton/blob/master/script/oltpbenchmark/testbed/measure-performance-tpcc.py

```
$ python measure-performance-tpcc.py hostname 15721 --client-threads=20
```

**Comment by sid1607** [comment]
I can look into this and #435

**Comment by apavlo** [comment]
@sid1607 Great. I realize that you're traveling this week, so just let me know if you can't get to it so that we can have somebody still around look at it.

**Comment by sid1607** [comment]
At a high level, I think this bug is because -

- I call TrafficCop::AbortQueryHelper() when 'ROLLBACK' is issued by the client
- AbortQueryHelper() is designed to always send an ErrorResponse as it assumes Query abortion is never supposed to happen

Since AbortTransaction is the required action from 'ROLLBACK', I think the fix is to not send an error response when 'ROLLBACK' is sent. This should be a quick fix.

**Comment by apavlo** [comment]
@sid1607 This fix works! The # of rejected has gone down. Trying it now with higher client thread counts

**Comment by sid1607** [comment]
Yes, I was just testing it too on MemSQL machines and it seems to be fine. Histograms show many unexpected errors, which I think are because of - https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/api/Worker.java#L422

I don't think these failures should be recorded under txnErrors?

**Comment by sid1607** [comment]
Also, I will issue a PR for this now

**Comment by apavlo** [comment]
@sid1607 I need to think about this. I think our logic is still incorrect. We don't have this problem with postgres. 

I will take care of this. Have a safe flight. Thanks for everything.

**Comment by sid1607** [comment]
Thanks! I'll try pitching in if issues are still open, once I reach
